# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='message',
        ),
        migrations.AddField(
            model_name='event',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Message', verbose_name='Reply to message'),
        ),
    ]
