# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('modified', models.DateField(auto_now=True, verbose_name='Updated at')),
                ('value', models.CharField(max_length=1000, verbose_name='Proper answer')),
                ('rule', models.CharField(choices=[('full_coincidence', 'Full coincidence'), ('to_be_in', 'To be in'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with'), ('contain_an_image', 'Contain an image'), ('contain_a_file', 'Contain a file'), ('contain_an_audio', 'Contain a audio'), ('contain_a_video', 'Contain a video'), ('received_before', 'Received before'), ('received_after', 'Received after')], default='full_coincidence', max_length=255, verbose_name='Step title')),
                ('requests', models.ForeignKey(default='FULL_COINCIDENCE', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='web.Request', verbose_name='Attached to requests')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
