# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='step',
        ),
        migrations.AddField(
            model_name='appuser',
            name='steps',
            field=models.ManyToManyField(blank=True, related_name='users', to='web.Step', verbose_name="User's level"),
        ),
    ]
