# Generated by Django 2.0 on 2017-12-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171230_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='links_preview',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='notifications',
        ),
        migrations.AddField(
            model_name='chat',
            name='no_links_preview',
            field=models.BooleanField(default=False, verbose_name='Disable links preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='no_notifications',
            field=models.BooleanField(default=False, verbose_name='Disable notifications'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='default_keyboard',
            field=models.TextField(blank=True, help_text='Chat menu, is used to inherit markup keyboard styles', max_length=1000, null=True, verbose_name='Default chat menu'),
        ),
    ]
