# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='requests',
            new_name='request',
        ),
    ]
