# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171123_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='device_uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Telegram user's id"),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Quest description'),
        ),
        migrations.AlterField(
            model_name='response',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Attached file'),
        ),
        migrations.AlterField(
            model_name='response',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Response message'),
        ),
        migrations.AlterField(
            model_name='response',
            name='redirect_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirected_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
