# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 10:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171223_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Message', verbose_name='Reply to message'),
        ),
    ]
