# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171126_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='step_on_error',
            field=models.SmallIntegerField(blank=True, help_text='Move to this step if mathematics expression wrongful', null=True, verbose_name='Step on error'),
        ),
        migrations.AddField(
            model_name='handler',
            name='step_on_success',
            field=models.SmallIntegerField(blank=True, help_text='Move to this step if mathematics expression truthful', null=True, verbose_name='Step on success'),
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.ForeignKey(blank=True, help_text='Response that contain this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.Response', verbose_name='Response'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='ids_expression',
            field=models.CharField(default='{}', help_text="Allowed / +*()! /. A set of rules by condition's id", max_length=500, verbose_name='Mathematics expression'),
        ),
    ]
