# Generated by Django 2.0 on 2018-01-05 14:57

import apps.web.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171230_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='redirects',
            field=models.ManyToManyField(blank=True, help_text='Users the message redirect to', to=settings.AUTH_USER_MODEL, verbose_name='Redirects'),
        ),
        migrations.AlterField(
            model_name='response',
            name='keyboard',
            field=models.TextField(blank=True, max_length=2000, null=True, validators=[apps.web.validators.array_field_validator], verbose_name='Keyboard layout'),
        ),
        migrations.AlterField(
            model_name='step',
            name='is_initial',
            field=models.BooleanField(),
        ),
    ]
