# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171127_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackQuery',
            fields=[
                ('created', models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at')),
                ('modified', models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Callback id')),
                ('data', models.TextField(help_text='Data associated with the callback button.', max_length=1000, verbose_name='Callback data')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('created', models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at')),
                ('modified', models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at')),
                ('id', models.BigIntegerField(help_text='Unique identifier for this chat.', primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('private', 'Private'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('channel', 'Channel')], max_length=255, verbose_name='Type')),
                ('title', models.CharField(blank=True, help_text='Title, for supergroups, channels and group chats.', max_length=255, null=True, verbose_name='title')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unique username')),
                ('first_name', models.CharField(blank=True, help_text='First name of the other party in a private chat', max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Last name of the other party in a private chat', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at')),
                ('modified', models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at')),
                ('update_id', models.BigIntegerField(db_index=True, verbose_name='Update Id')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='language_code',
            field=models.CharField(default='en', help_text='Language code from user messages got for the first time', max_length=10, verbose_name='Language code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 2, 8, 17, 40, 879888), help_text='Date the message was sent', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='forward_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender of the original message'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='modified',
            field=models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='modified',
            field=models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified',
            field=models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='modified',
            field=models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(help_text='Retrieved from Telegram API chat id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.Chat', verbose_name='Chat id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='modified',
            field=models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='modified',
            field=models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='response',
            name='modified',
            field=models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='step',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='step',
            name='modified',
            field=models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='update',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Bot', verbose_name='Bot from'),
        ),
        migrations.AddField(
            model_name='update',
            name='callback_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='web.CallbackQuery', verbose_name='Callback Query'),
        ),
        migrations.AddField(
            model_name='update',
            name='message',
            field=models.ForeignKey(help_text='Update action for particular massage', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='web.Message', verbose_name='Message ID'),
        ),
        migrations.AddField(
            model_name='callbackquery',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callbackquery',
            name='message',
            field=models.ForeignKey(help_text='Message with the callback button that originated the query.', on_delete=django.db.models.deletion.CASCADE, related_name='callback_queries', to='web.Message', verbose_name='Message ID'),
        ),
    ]
