# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 16:34
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20171223_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 16, 34, 47, 727044), verbose_name='Time to send on'),
        ),
        migrations.AlterField(
            model_name='step',
            name='number',
            field=models.SmallIntegerField(verbose_name='Step Number'),
        ),
    ]
