# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 16:35
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171223_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 23, 16, 35, 49, 157617, tzinfo=utc), verbose_name='Time to send on'),
        ),
    ]
