# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20171202_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbackquery',
            options={'verbose_name': 'Callback query', 'verbose_name_plural': 'Callback queries'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.RemoveField(
            model_name='message',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='message',
            name='response',
        ),
        migrations.AddField(
            model_name='update',
            name='handler',
            field=models.ForeignKey(blank=True, help_text='Handler contains expression needed to process a message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='web.Handler', verbose_name='Handler'),
        ),
        migrations.AddField(
            model_name='update',
            name='response',
            field=models.ForeignKey(blank=True, help_text='Response that contain this message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='web.Response', verbose_name='Response'),
        ),
    ]
