# Generated by Django 2.0 on 2018-01-24 16:59

import apps.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180105_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='update',
            name='response',
        ),
        migrations.AlterField(
            model_name='handler',
            name='ids_expression',
            field=models.CharField(blank=True, help_text='A set of math symbols to construct a particular rule,example: {} + {} > 1; example2: {cond_id} == 0;More details - http://pyparsing.wikispaces.com/file/view/arith.py/241810293/arith.py', max_length=500, null=True, validators=[apps.web.validators.condition_validator], verbose_name='Mathematics expression'),
        ),
    ]
