# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20171202_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='steps',
        ),
        migrations.AddField(
            model_name='handler',
            name='step',
            field=models.ForeignKey(default=9, help_text='Handle particular actions for this step', on_delete=django.db.models.deletion.CASCADE, related_name='handlers', to='web.Step'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handler',
            name='step_on_error',
            field=models.ForeignKey(blank=True, help_text='Move to this step if mathematics expression wrongful', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='false_handlers', to='web.Step', verbose_name='Step on error'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='step_on_success',
            field=models.ForeignKey(blank=True, help_text='Move to this step if mathematics expression truthful', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='true_handlers', to='web.Step', verbose_name='Step on success'),
        ),
    ]
