# Generated by Django 2.0 on 2017-12-24 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171223_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='matched_field',
        ),
        migrations.AddField(
            model_name='chat',
            name='_current_keyboard',
            field=models.TextField(blank=True, editable=False, help_text='Is used to define available command from keyboard', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='handler',
            name='enabled_on',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('button_text', 'Button text'), ('message_text', 'Message text'), ('callback_message_text', 'Callback message text'), ('callback data', 'Callback command')], default='button_text', help_text='Enabled only on following requests', max_length=255, verbose_name='Enabled on'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 19, 28, 24, 96493, tzinfo=utc), verbose_name='Time to send on'),
        ),
    ]
