# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20171205_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='User is a bot'),
        ),
    ]
