# Generated by Django 2.0 on 2017-12-24 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20171224_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='_current_keyboard',
            new_name='current_keyboard',
        ),
        migrations.AlterField(
            model_name='event',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 19, 34, 52, 144604, tzinfo=utc), verbose_name='Time to send on'),
        ),
    ]
