# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_appuser_is_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=2500, verbose_name='Message text'),
        ),
    ]
