# Generated by Django 2.0 on 2017-12-24 19:47

import datetime

from django.db import migrations, models
from django.utils.timezone import utc

import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20171224_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='matched_field',
            field=models.CharField(choices=[('any_message', 'Any message'), ('message_text', 'Message text'), ('callback_message_text', 'Callback message text'), ('callback data', 'Callback command')], default='any_message', max_length=255, verbose_name='Matched field'),
        ),
        migrations.AlterField(
            model_name='event',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 19, 47, 21, 226806, tzinfo=utc), verbose_name='Time to send on'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='enabled_on',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('button_click', 'Button click'), ('common_message', 'Common message'), ('callback_message', 'Callback message')], default='button_click', help_text='Enabled only on following requests', max_length=255, verbose_name='Enabled on'),
        ),
    ]
