# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 18:16
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20171206_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='requests',
            new_name='handler',
        ),
        migrations.RemoveField(
            model_name='response',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, help_text='Image attached to this message', null=True, upload_to='', verbose_name='Photo File'),
        ),
        migrations.AlterField(
            model_name='response',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='web.Message', verbose_name='Response message'),
        ),
    ]
