# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20171206_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSize',
            fields=[
                ('created', models.DateField(auto_now_add=True, help_text='Entity created at', verbose_name='Created at')),
                ('modified', models.DateField(auto_now=True, help_text='Entity created at', verbose_name='Updated at')),
                ('file_id', models.CharField(db_index=True, help_text='Unique identifier for this file.', max_length=1000, primary_key=True, serialize=False, unique=True, verbose_name='File ID')),
                ('width', models.IntegerField(verbose_name='Image width')),
                ('height', models.IntegerField(verbose_name='Image height')),
                ('file_size', models.IntegerField(verbose_name='File size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='photo',
        ),
        migrations.AddField(
            model_name='photosize',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.Message', verbose_name='From message'),
        ),
    ]
