# Generated by Django 2.0 on 2017-12-24 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20171224_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handler',
            name='on_button_click',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='on_callback_msg',
        ),
        migrations.RemoveField(
            model_name='handler',
            name='on_common_msg',
        ),
        migrations.AddField(
            model_name='handler',
            name='enabled_on',
            field=models.CharField(choices=[('button_click', 'Button click'), ('common_message', 'Common message'), ('callback_message', 'Callback message')], default='button_click', help_text='Enabled only on following requests', max_length=255, verbose_name='Enabled on'),
        ),
        migrations.AlterField(
            model_name='event',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 24, 20, 23, 53, 394962, tzinfo=utc), verbose_name='Time to send on'),
        ),
    ]
