# Generated by Django 2.0 on 2017-12-25 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20171224_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='callbackquery',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='callbackquery',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='event',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 11, 51, 41, 732411, tzinfo=utc), verbose_name='Time to send on'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='response',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='step',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='step',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='update',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='update',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at'),
        ),
    ]
