# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 18:53
from __future__ import unicode_literals

import apps.web.models.response
import apps.web.models.step
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20171206_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='step',
            name='status',
        ),
        migrations.AddField(
            model_name='appuser',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='web.Step', verbose_name="User's level"),
        ),
        migrations.AddField(
            model_name='quest',
            name='bot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='web.Bot', verbose_name='Connected bot'),
        ),
        migrations.AddField(
            model_name='response',
            name='as_reply',
            field=models.BooleanField(default=False, verbose_name='Send as reply'),
        ),
        migrations.AddField(
            model_name='response',
            name='keyboard',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Keyboard layout'),
        ),
        migrations.AddField(
            model_name='response',
            name='priority',
            field=models.SmallIntegerField(default=1, verbose_name='Priority in the queue'),
        ),
        migrations.AddField(
            model_name='step',
            name='is_initial',
            field=models.BooleanField(default=False, validators=[apps.web.models.step.only_initial]),
        ),
        migrations.AlterField(
            model_name='condition',
            name='rule',
            field=models.CharField(choices=[('full_coincidence', 'Full coincidence'), ('to_be_in', 'To be in'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with'), ('match_regex', 'Match regex'), ('contain_an_image', 'Contain an image'), ('contain_a_file', 'Contain a file'), ('contain_an_audio', 'Contain a audio'), ('contain_a_video', 'Contain a video'), ('received_before', 'Received before'), ('received_after', 'Received after')], default='full_coincidence', max_length=255, verbose_name='Step title'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='value',
            field=models.CharField(max_length=1000, verbose_name='Answer or pattern'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='ids_expression',
            field=models.CharField(blank=True, help_text="Allowed / +*()! /. A set of rules by condition's id", max_length=500, null=True, verbose_name='Mathematics expression'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, help_text='Retrieved from Telegram API chat id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='web.Chat', verbose_name='Chat id'),
        ),
        migrations.AlterField(
            model_name='response',
            name='message',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Message text'),
        ),
        migrations.RemoveField(
            model_name='response',
            name='redirect_to',
        ),
        migrations.AddField(
            model_name='response',
            name='redirect_to',
            field=models.TextField(blank=True, help_text='List of usernames separated by whitespace', max_length=1000, validators=[apps.web.models.response.username_list], verbose_name='Redirect to'),
        ),
    ]
