# Generated by Django 2.0 on 2017-12-25 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20171225_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Entity created at', null=True, verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Entity created at', null=True, verbose_name='Updated at')),
                ('file_id', models.CharField(db_index=True, help_text='Unique identifier for this file.', max_length=1000, verbose_name='File ID')),
                ('width', models.IntegerField(verbose_name='Image width')),
                ('height', models.IntegerField(verbose_name='Image height')),
                ('file_size', models.IntegerField(verbose_name='File size')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='web.Message', verbose_name='From message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='photosize',
            name='message',
        ),
        migrations.AlterField(
            model_name='event',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 25, 13, 2, 43, 689467, tzinfo=utc), verbose_name='Time to send on'),
        ),
        migrations.DeleteModel(
            name='PhotoSize',
        ),
    ]
