# Generated by Django 2.0 on 2017-12-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20171228_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='enabled_on',
            field=models.CharField(choices=[('reply_button', 'Reply button'), ('message', 'Message'), ('command', 'Command'), ('callback', 'Callback')], default='reply_button', help_text='Enabled only on following requests', max_length=255, verbose_name='Enabled on'),
        ),
    ]
