# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20171219_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='language_code',
            field=models.CharField(blank=True, help_text='Language code from user messages got for the first time', max_length=10, null=True, verbose_name='Language code'),
        ),
    ]
