# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20171219_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='matched_field',
            field=models.CharField(choices=[('any_message', "Callback's or message's text"), ('message_text', 'Message text'), ('callback_message_text', 'Callback message text'), ('callback data', 'Callback command')], default='any_message', max_length=255, verbose_name='Matched field'),
        ),
    ]
