# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_condition_matched_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='matched_field',
            field=models.CharField(choices=[('any_message', 'Any message'), ('message_text', 'Message text'), ('callback_message_text', 'Callback message text'), ('callback data', 'Callback command')], default='any_message', max_length=255, verbose_name='Matched field'),
        ),
        migrations.AlterField(
            model_name='update',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Update action for particular massage', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='web.Message', verbose_name='Message ID'),
        ),
    ]
