# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 19:27
from __future__ import unicode_literals

import apps.web.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20171222_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='delete_previous_keyboard',
            field=models.BooleanField(default=False, verbose_name='Delete previous keyboard'),
        ),
        migrations.AddField(
            model_name='response',
            name='inherit_keyboard',
            field=models.BooleanField(default=True, verbose_name='Save the last displayed keyboard'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='rule',
            field=models.CharField(choices=[('full_coincidence', 'Full coincidence'), ('to_be_in', 'To be in'), ('starts_with', 'Starts with'), ('ends_with', 'Ends with'), ('match_regex', 'Match regex'), ('contain_an_image', 'Contain an image'), ('contain_a_file', 'Contain a file'), ('contain_an_audio', 'Contain a audio'), ('contain_a_video', 'Contain a video'), ('received_before', 'Received before'), ('received_after', 'Received after')], default='full_coincidence', max_length=255, verbose_name='Pattern'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='ids_expression',
            field=models.CharField(blank=True, help_text="Allowed / +*()! /. A set of rules by condition's id", max_length=500, null=True, validators=[apps.web.validators.validate_conditions], verbose_name='Mathematics expression'),
        ),
    ]
