# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20171222_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='menu_markup',
            field=models.TextField(blank=True, help_text='Chat menu, is used to inherit markup keyboard styles', max_length=1000, null=True, verbose_name='Chat menu'),
        ),
    ]
