# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_chat_menu_markup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='menu_markup',
            new_name='default_keyboard',
        ),
        migrations.AddField(
            model_name='response',
            name='set_default_keyboard',
            field=models.BooleanField(default=True, verbose_name='Save this keyboard as default for chat'),
        ),
        migrations.AlterField(
            model_name='response',
            name='inherit_keyboard',
            field=models.BooleanField(default=True, verbose_name='Display last used keyboard'),
        ),
    ]
