# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20171222_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='delete_previous_keyboard',
            field=models.BooleanField(default=True, verbose_name='Delete previous keyboard'),
        ),
    ]
