# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20171222_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='one_time_keyboard',
            field=models.BooleanField(default=False, verbose_name='Hide keyboard after click on'),
        ),
    ]
